### ISSUE TITLE
Row pitch for other mip levels

### ISSUE THREAD

**Issue by W4RH4WK** [redorav/ddspp#1]
Does ddspp provide the row pitch for mipmap levels beyond the first one (level 0) directly?

If not, do you know how to calculate that from the information inside `Descriptor`?

Edit: I am trying to load a BC7 compressed texture with mipmaps.

**Comment by redorav** [comment]
Hi @W4RH4WK As far as I know to get the row pitch for any mip starting from the largest one, you shift the width as many times as you need to get to that mipmap's resolution, and then you multiply by the number of bytes per pixel, divided by the width of the block. Something like

`rowPitchMip3Bytes = (desc.width >> 2) * desc.bitsPerPixelOrBlock / (8 * desc.blockWidth);`

This deals with odd resolutions automatically as it's rounded down, and works regardless of whether the format is compressed or not (blockWidth == 1 when uncompressed). Let me know if that works for you, I can consider creating a convenience function and committing as soon as I can

**Comment by W4RH4WK** [comment]
```
(desc.width >> miplevel) * desc.bitsPerPixelOrBlock / (8 * desc.blockWidth)
```

Seems to work fine, although I've only tested a 2048x2048 texture.
I'll let you know once I encounter any issues with non-power-of-2 textures sizes.

It would be nice to have a convenience function `get_row_pitch`, akin to `get_offset`.

(Even with this convenience function present, I wouldn't remove the rowPitch member in the Descriptor.)

**Comment by redorav** [comment]
The correct solution is a bit more nuanced to cater for odd resolutions and some exotic format, I've provided two versions, one that uses the Descriptor and one where you pass the properties in directly. Let me know how they work out for you

**Comment by W4RH4WK** [comment]
Works great! Thanks a lot.

```c++
	std::vector<TextureInit> inits;
	for (auto mip = 0u; mip < ddsDesc.numMips; ++mip) {
		inits.push_back({
		    .data = ddsDataBody + ddspp::get_offset(ddsDesc, mip, 0),
		    .rowPitch = ddspp::get_row_pitch(ddsDesc, mip),
		});
	}
```
