### ISSUE TITLE
DXGI_Texture1D extents issue

### ISSUE THREAD

**Issue by EvilTrev** [redorav/ddspp#2]
Perhaps I'm missing something, but shouldn't this be height and depth? Not width?
```
case DXGI_Texture1D:
	desc.width = desc.height = 1;
	desc.type = Texture1D;
	break;
```

**Comment by redorav** [comment]
You're right, I'll fix that asap. It's very unusual to have 1D textures, what file are you loading or how are you creating it? I'd like to have one in data to have a test case

Thanks for reporting!

**Comment by redorav** [comment]
Closed via 4ae200de6f8d19a21ecf6ac6f071ba0184aa2a10

**Comment by EvilTrev** [comment]
I don't actually have a file, I just noticed it whilst checking out the code

**Comment by redorav** [comment]
Fair enough and good catch :) I tried creating a 1D texture using texconv and was unsuccessful, it keeps outputting a 2D texture and doesn't keep height as 1 because of hardware restrictions so in all honesty I'm not sure how I would test it on real content. Perhaps it's not used much
