### ISSUE TITLE
Possible bug with get_row_pitch

### ISSUE THREAD

**Issue by DarioSamo** [redorav/ddspp#4]
It seems this function will fail if the mip level is too high and width is low enough to the point where (width >> mip) results in 0.

Is this intended or should the value be clamped to 1 pixel wide at minimum?

https://github.com/redorav/ddspp/blob/4629460867c1d6a6e4326b5bec3e96835a18ab33/ddspp.h#L620-L626

**Comment by redorav** [comment]
Hmm I'm not sure what that case should return to be honest, 1 is a valid value and means it is a valid mipmap for the width you've provided. Returning 1 for any combination of width and mip doesn't make sense in my head. If I request mip 20 with a width of 256, should it return 1? Maybe it could return -1 to make it super obvious but it works for me with 0 as well.

So I understand your question better, is there a scenario where this has given you issues?

**Comment by DarioSamo** [comment]
> So I understand your question better, is there a scenario where this has given you issues?

Yes, a user-provided texture that is much bigger in one dimension than the other.

![image](https://github.com/user-attachments/assets/05e761f7-068b-4756-9c62-2e6f99e64119)

On RenderDoc the mipmaps display as such.

![image](https://github.com/user-attachments/assets/2c1551ae-db06-4db6-b6bf-9273fcb4d787)

The library returns a 0 for Mip #9 while RenderDoc shows a 1.

**Comment by redorav** [comment]
I see, I didn't realize those were the rules, they make sense now that I see them. Feel free to add a PR with a ternary that clamps to 1 and I'll approve right away. I'm guessing the clamp needs to apply to the width >> mip to work properly, not the final value

**Comment by DarioSamo** [comment]
What I did on my end is apply this to the operation and it does fix the issue:
```
std::max(width >> mip, 1U)
```
Would this be ok?

**Comment by redorav** [comment]
Same concept but without including the std library please, don't want to be adding the algorithm header for what is just a ternary comparison

**Comment by DarioSamo** [comment]
> Same concept but without including the std library please, don't want to be adding the algorithm header for what is just a ternary comparison

Fair enough, wasn't sure if this library already had made use of it or not.
