### ISSUE TITLE
get_offset can break with oddly sized mipmap chains.

### ISSUE THREAD

**Issue by DarioSamo** [redorav/ddspp#6]
The following file fails to retrieve the correct offset for this DDS file from mipmap level 5 and above.

[40E0F5A1#3#0_all.zip](https://github.com/user-attachments/files/16396061/40E0F5A1.3.0_all.zip)

RenderDoc displays it correctly.
![image](https://github.com/user-attachments/assets/e34dbfc8-0788-4e02-8f57-b966042646d9)
![image](https://github.com/user-attachments/assets/d3fe708f-317d-4b17-b212-5c6a23cdfc40)

While if I use get_offset, the result looks broken as the offset is wrong.
![image](https://github.com/user-attachments/assets/da76e907-947a-4d99-be97-727a92412e0e)

After tracking this down, I found out the get_offset implementation makes a few assumptions about how to downscale the mip0 size that might break when the texture uses non-power of two sizes.

I wrote this hacky workaround that only works with 4x4 block sizes to confirm my theory, and the texture loading was fixed.
```cpp
unsigned long long mipChainSize = 0;

for (unsigned int m = 0; m < desc.numMips; ++m)
{
    unsigned int blocksWide = (3 + std::max(desc.width >> m, 1U)) / 4;
    unsigned int blocksTall = (3 + std::max(desc.height >> m, 1U)) / 4;
    mipChainSize += blocksWide * blocksTall * desc.bitsPerPixelOrBlock;
    //unsigned long long mipSize = mip0Size >> 2 * m; // Divide by 2 in width and height
    //mipChainSize += mipSize > desc.bitsPerPixelOrBlock ? mipSize : desc.bitsPerPixelOrBlock;
}

offset += mipChainSize * slice;

for (unsigned int m = 0; m < mip; ++m)
{
    unsigned int blocksWide = (3 + std::max(desc.width >> m, 1U)) / 4;
    unsigned int blocksTall = (3 + std::max(desc.height >> m, 1U)) / 4;
    offset += blocksWide * blocksTall * desc.bitsPerPixelOrBlock;
    //unsigned long long mipSize = mip0Size >> 2 * m; // Divide by 2 in width and height
    //offset += mipSize > desc.bitsPerPixelOrBlock ? mipSize : desc.bitsPerPixelOrBlock;
}
```
So it seems like the issue is tied potentially to the offset computation not handling the cases where the size rounds down.

I can look into making a fix but I'm not sure I understand the issue correctly quite yet. Any input on this?

**Comment by redorav** [comment]
Hi Dario thanks for reporting. I'm away on holiday until the 3rd of August and will take a look when I'm back. I'll take a look at the PR as well

**Comment by DarioSamo** [comment]
Hi Emilio, no pressure, I've patched this on my side in the meantime until you get time to review it. Thanks!
